send_command:
  description: Send device command through RFPlayer.
  fields:
    command:
      name: Command
      description: The command to be sent. [add Protocol]
      required: true
      default: " " 
      example: "HELLO"
      selector:
        select:
          options:
              - " "
              - 1 FACTORYRESET. FORMAT JSON. STATUS. JAMMING 7. JAMMING SIMULATE
              - HELLO
              - PING
              - "ON"
              - "OFF"
              - DIM %4
              - ASSOC
              - DISSOC
              - ASSOC_OFF
              - DISSOC_OFF
              - ALL_ON
              - ALL_OFF
              - RECEIVER + *
              - REPEATER + *
              - REPEATER ON
              - REPEATER OFF
              - LEDACTIVITY 0
              - LEDACTIVITY 1
              - DIM %4
              - ASSOC
              - DISSOC
              - ASSOC_OFF
              - DISSOC_OFF
              - ALL_ON
              - ALL_OFF
              - JAMMING 7
              - JAMMING SIMULATE
              - EDISIOFRAME
              - FREQ L 433920
              - FREQ L 433420
              - FREQ L 0
              - FREQ H 868950
              - FREQ H 868350
              - FREQ H 0
              - SELECTIVITY L 4
              - SELECTIVITY H 4
              - SENSITIVITY L 4
              - SENSITIVITY H 4
              - DSPTRIGGER L 6
              - DSPTRIGGER H 8
              - RFLINK 0
              - RFLINK 1
              - RFLINKTRIGGER L 12
              - RFLINKTRIGGER H 10
              - LBT 16
              - FORMAT RFLINK OFF
              - FORMAT RFLINK BINARY
              - " "
          mode: dropdown
    protocol:
      name: Protocol
      description: RFPlayer compatible protocol.[parametre]
      required: true
      example: CHACON
      selector:
        select:
          options:
              - " "
              - "BLYSS"
              - "CHACON"
              - "DOMIA"
              - "EDISIO"
              - "EDISIOFRAME"
              - "FS20"
              - "JAMMING"
              - "JAMMING SIMULATE"
              - "KD101"
              - "OREGON"
              - "OREGONV1"
              - "OREGONV2"
              - "OREGONV3/OWL"
              - "OWL"
              - "PARROT"
              - "RTS"
              - "TIC"
              - "VISONIC"
              - "VISONIC433"
              - "VISONIC868"
              - "X10"
              - "X2D"
              - "X2D433"
              - "X2D868"
              - "X2DELEC"
              - "X2DGAS"
              - "X2DSHUTTER"
              - " "
          mode: dropdown
    device_address:
      name: Device address
      description: Device address.
      required: false
      example: A1
      selector:
        text:
    device_id:
      name: Device ID
      description: Device ID.
      required: false
      example: 40
      selector:
        text:
    automatic_add:
      name: Create entity
      description: Create associated switch entity
      required: true
      default: false
      selector:
        boolean:
    entity_type:
      name: Entity type
      description: Type of entity created
      required: false
      default: switch
      selector:
        select:
          options:
              - "switch"
              - "cover"
              - "number"
              - "sensor"
          mode: dropdown
